apiVersion: arbiter.k8s.com.cn/v1alpha1
kind: ObservabilityIndicant
metadata:
  name: prometheus-pod-mem
spec:
  metric:
    historyLimit: 1
    metricIntervalSeconds: 30
    metrics:
      memory:
        aggregations: []
        description: memory
        query: sum by (pod) (container_memory_working_set_bytes{namespace="{{.metadata.namespace}}",pod="{{.metadata.name}}",container!="",container!="POD"})
        unit: byte
    timeRangeSeconds: 3600
  source: prometheus
  targetRef:
    group: ""
    index: 0
    kind: Pod
    labels:
      app: mem-cost
    name: ""
    namespace: arbiter-system
    version: v1
status:
  conditions: []
  phase: ""
  metrics: {}

