apiVersion: arbiter.k8s.com.cn/v1alpha1
kind: ObservabilityIndicant
metadata:
  name: prometheus-pod-cpu
spec:
  metric:
    historyLimit: 1
    metricIntervalSeconds: 30
    metrics:
      cpu:
        aggregations: []
        description: cpu
        query: (sum(rate(container_cpu_usage_seconds_total{namespace="{{.metadata.namespace}}",pod="{{.metadata.name}}",container!="POD",container!=""}[5m])) by (pod))*1000
        unit: 'm'
    timeRangeSeconds: 3600
  source: prometheus
  targetRef:
    group: ""
    index: 0
    kind: Pod
    labels:
      app: mem-cost
    name: ""
    namespace: arbiter-system
    version: v1
status:
  conditions: []
  phase: ""
  metrics: {}

