apiVersion: arbiter.k8s.com.cn/v1alpha1
kind: ObservabilityIndicant
metadata:
  name: metric-server-pod-mem
spec:
  metric:
    historyLimit: 1
    # metric-server collect metrics every 15 seconds
    metricIntervalSeconds: 15
    metrics:
      memory:
        aggregations:
        - time
        description: memory
        query: ""
        unit: byte
    timeRangeSeconds: 3600
  source: metric-server
  targetRef:
    group: ""
    index: 0
    kind: Pod
    labels:
      app: mem-cost
    namespace: arbiter-system
    version: v1
status:
  conditions: []
  phase: ""
  metrics: {}

