apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.observer.prometheusServer.nameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.observer.prometheusServer.nameOverride }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.observer.prometheusServer.nameOverride }}
    spec:
      containers:
        - command:
            - observer-prometheus-server
            - -address={{ .Values.observer.prometheusServer.address }}
            - -v=4
          image: {{ .Values.observer.prometheusServer.image.serverImage }}
          imagePullPolicy: {{ .Values.observer.prometheusServer.image.pullPolicy }}
          name: server
          resources:
{{ toYaml .Values.observer.resources | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
        - command:
            - observer
          image:  {{ .Values.observer.prometheusServer.image.observerImage }}
          imagePullPolicy: {{ .Values.observer.prometheusServer.image.pullPolicy }}
          name: obi-controller
          resources:
{{ toYaml .Values.observer.resources | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: {{ .Values.observer.serviceAccountName }}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: sock-volume
