{{- $less := eq (include "le20" .) "true" -}}
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: {{ .Values.scheduler.nameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --config=/etc/kubernetes/kube-scheduler-arbiter-config.yaml
        - --v=4
      {{- if $less }}
      image: {{ .Values.scheduler.image }}:pre-{{ .Values.scheduler.tag }}
      {{- else }}
      image: {{ .Values.scheduler.image }}:{{ .Values.scheduler.tag }}
      {{- end }}
      imagePullPolicy: {{ .Values.scheduler.pullPolicy }}
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      name: kube-scheduler
      resources:
{{ toYaml .Values.scheduler.resources | indent 8 }} 
      startupProbe:
        failureThreshold: 24
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubernetes/kube-scheduler-arbiter-config.yaml
          name: config
          subPath: kube-scheduler-arbiter-config.yaml
          readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  serviceAccountName: {{ .Values.scheduler.serviceAccountName }}
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
      name: kubeconfig
    - configMap:
        name: {{ .Values.scheduler.configMapName }}
      name: config
