apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.observer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityindicants
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - ""
      - metrics.k8s.io
    resources:
      - pods
      - services
      - services/proxy
      - nodes
      - events
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability
subjects:
  - kind: ServiceAccount
    name: {{ .Values.observer.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: observability
  apiGroup: rbac.authorization.k8s.io
