//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Arbiter Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	schedulerconfig "github.com/kube-arbiter/arbiter/pkg/apis/schedulerconfig"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ArbiterArgs)(nil), (*schedulerconfig.ArbiterArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ArbiterArgs_To_schedulerconfig_ArbiterArgs(a.(*ArbiterArgs), b.(*schedulerconfig.ArbiterArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*schedulerconfig.ArbiterArgs)(nil), (*ArbiterArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_schedulerconfig_ArbiterArgs_To_v1beta1_ArbiterArgs(a.(*schedulerconfig.ArbiterArgs), b.(*ArbiterArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ArbiterArgs_To_schedulerconfig_ArbiterArgs(in *ArbiterArgs, out *schedulerconfig.ArbiterArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.KubeConfigPath, &out.KubeConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ArbiterArgs_To_schedulerconfig_ArbiterArgs is an autogenerated conversion function.
func Convert_v1beta1_ArbiterArgs_To_schedulerconfig_ArbiterArgs(in *ArbiterArgs, out *schedulerconfig.ArbiterArgs, s conversion.Scope) error {
	return autoConvert_v1beta1_ArbiterArgs_To_schedulerconfig_ArbiterArgs(in, out, s)
}

func autoConvert_schedulerconfig_ArbiterArgs_To_v1beta1_ArbiterArgs(in *schedulerconfig.ArbiterArgs, out *ArbiterArgs, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.KubeConfigPath, &out.KubeConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_schedulerconfig_ArbiterArgs_To_v1beta1_ArbiterArgs is an autogenerated conversion function.
func Convert_schedulerconfig_ArbiterArgs_To_v1beta1_ArbiterArgs(in *schedulerconfig.ArbiterArgs, out *ArbiterArgs, s conversion.Scope) error {
	return autoConvert_schedulerconfig_ArbiterArgs_To_v1beta1_ArbiterArgs(in, out, s)
}
