apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-prometheus
spec:
  selector:
    matchLabels:
      app: observer-prometheus
  template:
    metadata:
      labels:
        app: observer-prometheus
    spec:
      containers:
        - command:
            - observer-prometheus-server
            - -address=http://prometheus-server.kube-system.svc.cluster.local
          image:  kubearbiter/observer-prometheus-server:v0.1.0
          name: prometheus-plugin
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "echo 'hello'|nc local:/var/run/observer.sock"]
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
        - command:
            - observer
          image: kubearbiter/observer:v0.1.0
          name: obi-controller
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
      serviceAccount: observability
      serviceAccountName: observability
      volumes:
        - emptyDir: {}
          name: sock-volume
