apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-cost
  labels:
    app: mem-cost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-cost
  template:
    metadata:
      labels:
        app: mem-cost
    spec:
      containers:
      - name: mem-cost
        image: kubearbiter/resource-consumer:1.10
        command:
        - stress
        args:
        - -m
        - "2"
        - --vm-bytes
        - 32M
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
