apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-resource-tagger
spec:
  selector:
    matchLabels:
      arbiter-component: executor-resource-tagger
  template:
    metadata:
      labels:
        arbiter-component: executor-resource-tagger
    spec:
      containers:
        - image: kubearbiter/executor-resource-tagger:v0.1.0
          name: executor-resource-tagger
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /plugins
              name: shared-volume
        - args:
            - -endpoint=/plugins/resourcetagger.sock
          command:
            - /bin/executor
          image: kubearbiter/executor:v0.1.0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: executor
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /plugins
              name: shared-volume
      serviceAccount: executor
      serviceAccountName: executor
      volumes:
        - emptyDir: {}
          name: shared-volume
