// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: pkg/proto/executor.proto

package executor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExecuteClient is the client API for Execute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecuteClient interface {
	ExecuteAction(ctx context.Context, in *ExecuteActionMessage, opts ...grpc.CallOption) (*ExecuteActionResponse, error)
	Execute(ctx context.Context, in *ExecuteMessage, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type executeClient struct {
	cc grpc.ClientConnInterface
}

func NewExecuteClient(cc grpc.ClientConnInterface) ExecuteClient {
	return &executeClient{cc}
}

func (c *executeClient) ExecuteAction(ctx context.Context, in *ExecuteActionMessage, opts ...grpc.CallOption) (*ExecuteActionResponse, error) {
	out := new(ExecuteActionResponse)
	err := c.cc.Invoke(ctx, "/execute.Execute/ExecuteAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeClient) Execute(ctx context.Context, in *ExecuteMessage, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/execute.Execute/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecuteServer is the server API for Execute service.
// All implementations must embed UnimplementedExecuteServer
// for forward compatibility
type ExecuteServer interface {
	ExecuteAction(context.Context, *ExecuteActionMessage) (*ExecuteActionResponse, error)
	Execute(context.Context, *ExecuteMessage) (*ExecuteResponse, error)
	mustEmbedUnimplementedExecuteServer()
}

// UnimplementedExecuteServer must be embedded to have forward compatible implementations.
type UnimplementedExecuteServer struct {
}

func (UnimplementedExecuteServer) ExecuteAction(context.Context, *ExecuteActionMessage) (*ExecuteActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedExecuteServer) Execute(context.Context, *ExecuteMessage) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedExecuteServer) mustEmbedUnimplementedExecuteServer() {}

// UnsafeExecuteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecuteServer will
// result in compilation errors.
type UnsafeExecuteServer interface {
	mustEmbedUnimplementedExecuteServer()
}

func RegisterExecuteServer(s grpc.ServiceRegistrar, srv ExecuteServer) {
	s.RegisterService(&Execute_ServiceDesc, srv)
}

func _Execute_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/execute.Execute/ExecuteAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteServer).ExecuteAction(ctx, req.(*ExecuteActionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Execute_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/execute.Execute/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteServer).Execute(ctx, req.(*ExecuteMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Execute_ServiceDesc is the grpc.ServiceDesc for Execute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Execute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execute.Execute",
	HandlerType: (*ExecuteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteAction",
			Handler:    _Execute_ExecuteAction_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Execute_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/executor.proto",
}
